//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanOto.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public string MaLog { get; set; }
        public string UserName { get; set; }
        public string Messages { get; set; }
        public Nullable<System.DateTime> TimeLogin { get; set; }
        public Nullable<System.DateTime> TimeLogout { get; set; }
        public Nullable<System.DateTime> TimeCreate { get; set; }
        public string Type { get; set; }
        public bool IsRead { get; set; }
    
        public virtual User User { get; set; }
    }
}
